server:
  hostname: localhost
  port: 8080
  certs:
    cert: server.crt
    key: server.key
  repo:
    type: file
    path: ./files/
  publish:
    maxSize: 204800
  auth:
    enabled: false
  packageCollections:
    enabled: true
    requirePackageJson: false